name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  run-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python (if required)
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Linux commands
        run: |
          echo "Installing dependencies"
          pip install -r requirements.txt
          sphinx-build -b html . build/html
          echo "Done!"
